### ISSUE TITLE
Issues when prerendering subfolder pages

### ISSUE THREAD

**Issue by KayoticSully** [juranki/sveltekit-cdk#11]
I'm working on deploying a site and I have found that if any page in a subfolder route (like `/src/routes/about/faq.svelte` or similar) is prerendered then directly accessing the page will throw an AWS access error. And non pre-rendered pages in the same folder will entirely fail to load.

This is because the CloudFront Distribution Behaviors are setup to load `/folder/*` (in this example `/about/*`) from the s3 origin.  Only the default behavior runs through the @edge lambda. These sub folders will not load the index.html file. For example `/about/faq` won't load when directly accessed since S3 will try to serve `s3:bucket/about/faq.html` however SvelteKit renders it out as `/about/faq/index.html`. This is partly an AWS/CF/S3 issue.  However, I would like to try and solve this.

### Solution Part 1
When creating the static file behaviors for the CF Distribution process non "reserved" static asset folders (like `_app`, `assets`, etc), recursively and add the s3 behavior **only** to each individual prerendered page. This **should** force the dynamic pages to fallback to the lambda and render properly.

But this only solves one of the issues

### Solution Part 2
Update the lambda to re-write the URL to include the `/index.html` at the end if the page is a pre-rendered page rather than try and render the page. So it will fetch it from the right place.

This does force all sub-pages to go through the lambda but directly accessing sub-folder pages does not work currently if you want to pre-render them at all.

### Part 2 Alternate Solution
An alternate approach to the second part to try and avoid using the lambda at all would be to rename the files before/when they are uploaded to s3 so it does not have to load `index.html` but just the expected file. This just hit me while I was writing this up so I haven't entirely thought through it. There could be collision issues maybe? But its another approach at least.

Are there any thoughts on these approaches? Have they been tried/considered before and maybe there are issues I'm not thinking about?

**Comment by juranki** [comment]
I expected that CloudFront configuration would be the most difficult part to get right, but I don't have a prepared plan for it.

One more partial solution in addition to the ones you mentioned would be to preprocess requests with a CloudFront function to make it easier to configure the CF behaviors.

But anyway, first I'll create a minimal SvelteKit app that reproduces the problem. So far I've used mostly the demo app and it's clearly not sufficient any more.

**Comment by juranki** [comment]
Added minimal [site that demonstrates the problem](https://github.com/juranki/sveltekit-cdk/tree/%2311/packages/test/src/routes) (deployed here: https://d3a63laq3irdpc.cloudfront.net)

**Comment by juranki** [comment]
@KayoticSully 
I started with renaming the pre-rendered files so S3 can server them directly. I think collisions are quite unlikely.

Having pre-rendered and dynamic pages or endpoints in same folders is more difficult.
Adding behaviours for all pre-rendered pages is problematic because there could be thousands of them and behaviours have soft limit of 25.

Would it be terrible if the adapter checked that and refused to build if pre-rendered and SSR were mixed under same top level route?

Are you using lambda@edge or regular lambda? It might be possible to place lambda@edge SSR to origin request handler so that it handles the request if it hits dynamic page or endpoint, and otherwise passes the request on to the origin (s3). If that worked, it would allow mixing pre-rendered and dynamic pages in same folders. But with that approach regular lambda doesn't fit to the same pattern.

**Comment by juranki** [comment]
![image](https://user-images.githubusercontent.com/6607/153515499-958e7fad-058f-47a4-b318-0d6d3170d3db.png)
